# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='db_escrita',
            fields=[
                ('posicao_paragrafo', models.AutoField(primary_key=True, serialize=False)),
                ('paragrafo', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='db_participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_rodada', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='db_sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('timer', models.IntegerField()),
                ('n_rodada', models.IntegerField()),
                ('max_participantes', models.IntegerField()),
                ('participantes', models.ManyToManyField(to='salas.db_participante')),
            ],
        ),
    ]
